#!/bin/bash
# =============================================================================
# ABLATION STUDY — Synthetic datasets (4 cases × 4 modes)
#
# Cases are generated by generate_synthetic_test.py, each targeting one loss:
#   test_cap      star     10 frames  varying saliency   → L_cap_res
#   test_cvt      L-shape  12 frames  uniform            → L_cvt_norm
#   test_fea      crescent  8 frames  uniform            → L_fea
#   test_combined donut    10 frames  mixed              → all 3
#
# Key flags:
#   --no-filter-frames-by-isnet   (synthetic frames have no real salient objects)
#   rm -rf isnet_output/          (clear stale cache before each run)
# =============================================================================

eval "$(conda shell.bash hook)"
conda activate yoloe

CAST_DIR="$(cd "$(dirname "$0")" && pwd)"
DATA_ROOT="/home/serverai/ltdoanh/LayoutGeneration/FINAL_data"
SYNTH_BASE="${DATA_ROOT}/synthetic_tests"
OUTPUT_BASE="${DATA_ROOT}/layout/ablation_loss_synth_v3"

ABLATION_MODES=("full" "wo_cap" "wo_cvt" "wo_fea")

CASES=(
    "test_cap"
    "test_cvt"
    "test_fea"
    "test_combined"
)

# ─────────────────────────────────────────────────────────────
# Helper
# ─────────────────────────────────────────────────────────────
run_one() {
    local mask="$1"
    local frames="$2"
    local outdir="$3"
    local mode="$4"
    local label="$5"

    echo ""
    echo "================================================================"
    echo " [${label}]  mode=${mode}"
    echo "   mask   = ${mask}"
    echo "   frames = ${frames}"
    echo "   out    = ${outdir}"
    echo "================================================================"

    mkdir -p "${outdir}"

    # Clear stale ISNet cache to force fresh summary.json without _mask.png files
    rm -rf "${outdir}/isnet_output"

    local ablation_flag=""
    if [ "${mode}" != "full" ]; then
        ablation_flag="--ablation=${mode}"
    fi

    python run.py \
        "${mask}" \
        "${frames}" \
        "${outdir}" \
        2 \
        --shape-is-mask \
        --no-filter-frames-by-isnet \
        ${ablation_flag} \
        2>&1 | tee "${outdir}/console.log"

    local logfile="${outdir}/run.log"
    if [ -f "${logfile}" ]; then
        local dead last
        dead=$(grep --text "cells are invalid" "${logfile}" | tail -1 || true)
        last=$(grep --text "\[iter " "${logfile}" | tail -1 || true)
        echo "  >>> DEAD CELLS: ${dead:-0 (none)}"
        echo "  >>> FINAL LOSS: ${last}"
    fi
    echo "  >>> DONE: ${label} / ${mode}"
}

# ─────────────────────────────────────────────────────────────
# Run experiments
# ─────────────────────────────────────────────────────────────
echo ""
echo "=============================================================="
echo " Synthetic Ablation  (${#CASES[@]} cases × ${#ABLATION_MODES[@]} modes)"
echo "=============================================================="

for case_name in "${CASES[@]}"; do
    MASK="${SYNTH_BASE}/${case_name}/shape_mask.png"
    FRAMES="${SYNTH_BASE}/${case_name}/frames"

    if [ ! -f "${MASK}" ]; then
        echo "[SKIP] Mask not found: ${MASK}  (run generate_synthetic_test.py first)"
        continue
    fi
    if [ ! -d "${FRAMES}" ] || [ -z "$(ls -A "${FRAMES}" 2>/dev/null)" ]; then
        echo "[SKIP] No frames in: ${FRAMES}"
        continue
    fi

    n_frames=$(find "${FRAMES}" -maxdepth 1 -name '*.jpg' | wc -l)
    echo ""
    echo "━━━ ${case_name}  (${n_frames} frames) ━━━"

    for mode in "${ABLATION_MODES[@]}"; do
        run_one "${MASK}" "${FRAMES}" "${OUTPUT_BASE}/${case_name}/${mode}" \
                "${mode}" "${case_name}"
    done
done

# ─────────────────────────────────────────────────────────────
# Summary table
# ─────────────────────────────────────────────────────────────
echo ""
echo "=============================================================="
echo " SUMMARY"
echo "=============================================================="

CSV="${OUTPUT_BASE}/summary.csv"
echo "case,mode,valid,total,n_frames,cap_res,cvt_norm,fea,AD,ARD" > "${CSV}"

printf "\n%-16s %-8s %-9s %-7s %-12s %-12s %-12s %-8s %-8s\n" \
    "Case" "Mode" "Valid" "Frames" "cap_res" "cvt_norm" "fea" "AD" "ARD"
echo "$(printf '%0.s-' {1..95})"

for case_name in "${CASES[@]}"; do
    for mode in "${ABLATION_MODES[@]}"; do
        out="${OUTPUT_BASE}/${case_name}/${mode}"
        log="${out}/run.log"
        met="${out}/layout_metrics.csv"
        [ -f "${log}" ] || continue

        valid=$(grep --text "Valid cells:" "${log}" | tail -1 | grep -oP 'Valid cells: \K\d+' || echo "?")
        total=$(grep --text "Valid cells:" "${log}" | tail -1 | grep -oP '/\K\d+' || echo "?")
        n_ld=$(grep --text -oP 'Processing \K\d+ frames' "${log}" | head -1 || echo "?")
        last=$(grep --text "\[iter " "${log}" | tail -1 || true)
        cap=$(echo "${last}" | grep -oP 'cap_res=\K[0-9.]+' || echo "N/A")
        cvt=$(echo "${last}" | grep -oP 'cvt_norm=\K[0-9.]+' || echo "N/A")
        fea=$(echo "${last}" | grep -oP '\bfea=\K[0-9.]+' || echo "N/A")
        ad="N/A"; ard="N/A"
        if [ -f "${met}" ]; then
            ad=$(awk  -F',' 'NR==2 {print $4}' "${met}")
            ard=$(awk -F',' 'NR==2 {print $6}' "${met}")
        fi

        echo "${case_name},${mode},${valid},${total},${n_ld},${cap},${cvt},${fea},${ad},${ard}" >> "${CSV}"
        printf "%-16s %-8s %2s/%-6s %-7s %-12s %-12s %-12s %-8s %-8s\n" \
            "${case_name}" "${mode}" "${valid}" "${total}" \
            "${n_ld}" "${cap}" "${cvt}" "${fea}" "${ad}" "${ard}"
    done
done

echo ""
echo "  Summary: ${CSV}"
echo ""
echo "ALL SYNTHETIC ABLATION EXPERIMENTS COMPLETE."
