device: cuda
input_path: /home/serverai/ltdoanh/LayoutGeneration/outputs/test_transnetv2_h264_21724_20251122_151343/cartoon_detection/predict
model_path: /home/serverai/ltdoanh/LayoutGeneration/objectfree/weight_model/yoloe/weights/best_general.pt
pe_path: /home/serverai/ltdoanh/LayoutGeneration/objectfree/weight_model/character-pe.pt
prompt: 'characters '
save_path: /home/serverai/ltdoanh/LayoutGeneration/outputs/inference_comparison_test3_0.1/trained
threshold: 0.2
type_content: image
