# =========================================================
# TOKENS
# =========================================================
tokens:
  sam3: "hf_REDACTED"          
  dinov3: "hf_REDACTED"        

# =========================================================
# SAM3 CONFIG
# =========================================================
sam3:
  text_prompt: "anime character, object"
  score_thresh: 0.1

# =========================================================
# DINOv3 CONFIG
# =========================================================
dinov3:
  model_name: "facebook/dinov3-vitl16-pretrain-lvd1689m"
  cache_dir: "home/serverai/ltdoanh/LayoutGeneration/objectfree/Dinov3/weights/dinov3"

# =========================================================
# CHARACTER BANK
# =========================================================
bank:
  high_score_thresh: 0.5
  match_sim_thresh: 0.7

# =========================================================
# IO
# =========================================================
io:
  input_folder: "/home/serverai/ltdoanh/LayoutGeneration/data/FINAL/keyframe/63592/keyframes"
  output_root: "/home/serverai/ltdoanh/LayoutGeneration/data/FINAL/test/object_free/63592"

# =========================================================
# RUNTIME
# =========================================================
runtime:
  device: "cuda"          # cuda | cpu
  min_box_size: 20
  max_images: null        # null = all images
  verbose: true

# =========================================================
# MODE FLAGS
# =========================================================
mode:
  visualize: true         # true = save bbox images
  save_json: true         # true = save json result
  draw_rejected: true     # false = only draw kept objects
