#!/usr/bin/env python3
"""
Compare Per-Attribute MPR using a Radar Chart.
Input: JSON files generated by eval_*.py (fast mode updated).

Usage:
    python scripts/compare_attr_radar.py \
        --inputs "Ours:path/to/v11_gaps.json" "VSUMM:path/to/vsumm_gaps.json" \
        --output attr_radar.png
"""

import argparse
import json
import numpy as np
import matplotlib.pyplot as plt
from math import pi

# Attribute names matching JSON keys (percentile_{name})
ATTR_NAMES = ["sharpness", "colorfulness", "brightness", "sakuga", "cinematic", "expression"]

def load_data(inputs):
    data = {}
    for item in inputs:
        try:
            label, path = item.split(":", 1)
            with open(path, 'r') as f:
                data[label] = json.load(f)
        except Exception as e:
            print(f"Error loading '{item}': {e}")
    return data

def plot_radar(data, output_path):
    attributes = [a.capitalize() for a in ATTR_NAMES]
    N = len(attributes)
    
    angles = [n / float(N) * 2 * pi for n in range(N)]
    angles += angles[:1]
    
    fig, ax = plt.subplots(figsize=(9, 9), subplot_kw=dict(polar=True))
    
    # Axes
    plt.xticks(angles[:-1], attributes, size=11, weight='bold')
    
    # Y-ticks
    ax.set_rlabel_position(0)
    plt.yticks([0.2, 0.4, 0.6, 0.8, 1.0], ["0.2", "0.4", "0.6", "0.8", "1.0"], color="grey", size=8)
    plt.ylim(0, 1.05)
    
    # Data
    colors = ['#FF4500', '#1E90FF', '#32CD32', '#FFD700', '#8A2BE2'] # Custom vibrant colors
    i = 0
    
    for label, metrics in data.items():
        # Extract values
        values = []
        for name in ATTR_NAMES:
            key = f"percentile_{name}"
            val = metrics.get(key, 0.5) # Default to 0.5 (random)
            values.append(val)
        
        values += values[:1]
        
        color = colors[i % len(colors)]
        ax.plot(angles, values, linewidth=2, linestyle='solid', label=label, color=color)
        ax.fill(angles, values, color=color, alpha=0.15)
        i += 1
        
        # Print table row
        print(f"{label}: " + ", ".join([f"{v:.3f}" for v in values[:-1]]))

    # Legend
    plt.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1))
    
    plt.title("Per-Attribute Aesthetic Quality (Percentile Rank)\nHigher is Better (1.0 = Best in Video)", 
              size=14, weight='bold', y=1.08)
    
    # Guidelines
    # Random selection is ~0.5
    angles_poly = [n / float(N) * 2 * pi for n in range(N)]
    angles_poly += angles_poly[:1]
    ax.plot(angles_poly, [0.5]*(N+1), color='black', linestyle='--', linewidth=1, alpha=0.5, label='Random')
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"\n✅ Attribute Radar chart saved to {output_path}")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--inputs", nargs="+", required=True, help="Label:Path list")
    parser.add_argument("--output", type=str, default="attr_radar.png")
    args = parser.parse_args()
    
    data = load_data(args.inputs)
    if data:
        plot_radar(data, args.output)

if __name__ == "__main__":
    main()
