#!/usr/bin/env python3
"""
Compare multiple models using a Radar Chart on the entire dataset.
Input: JSON files generated by eval_v11_gaps.py, eval_vsumm_gaps.py, eval_llmvs_gaps.py.

Usage:
    python scripts/compare_radar_chart.py \
        --inputs "Ours:path/to/v11_gaps.json" "VSUMM:path/to/vsumm_gaps.json" \
        --output comparison_radar.png
"""

import argparse
import json
import numpy as np
import matplotlib.pyplot as plt
import os
from math import pi
import pandas as pd

# Metric definitions: Display Name -> {JSON Key, Goal}
METRICS = {
    "MPR (Aesthetic)":       {"key": "mpr_mean",       "goal": "max"},
    "Top10 (Aesthetic)":     {"key": "top10_mean",     "goal": "max"},
    "TempCov (Diversity)":   {"key": "temp_cov_mean",  "goal": "max"},
    "RecErr (Repres.)":      {"key": "feat_gap_mean",  "goal": "min"},
    "Frechet (Repres.)":     {"key": "frechet_mean",   "goal": "min"},
    "DISTS Gap":             {"key": "dists_gap_mean", "goal": "min"},
    "LPIPS Gap":             {"key": "lpips_gap_mean", "goal": "min"},
}

def load_data(inputs):
    """Load JSON data from input strings 'Label:Path'."""
    data = {}
    for item in inputs:
        try:
            label, path = item.split(":", 1)
            with open(path, 'r') as f:
                data[label] = json.load(f)
        except ValueError:
            print(f"Error parsing input '{item}'. Format should be Label:Path")
        except FileNotFoundError:
            print(f"Error: File not found '{path}'")
        except Exception as e:
            print(f"Error loading '{path}': {e}")
    return data

def normalize_scores(data):
    """
    Normalize scores for Radar Chart (0.0 to 1.0).
    For 'max' goal: val / max_val
    For 'min' goal: min_val / val (Efficiency score)
    Returns:
        norm_scores: {Label: [v1, v2, ...]}
        raw_values:  {Label: [v1, v2, ...]}
        categories:  [Metric Names]
    """
    categories = list(METRICS.keys())
    labels = list(data.keys())
    
    # Extract raw values first
    raw_values = {l: [] for l in labels}
    
    # Calculate min/max for normalization
    stats = {} 
    
    for cat in categories:
        key = METRICS[cat]["key"]
        goal = METRICS[cat]["goal"]
        
        vals = []
        for l in labels:
            val = data[l].get(key, float('nan'))
            if val is None: val = float('nan')
            vals.append(val)
            raw_values[l].append(val)
        
        # Filter NaNs for stats
        param_vals = [v for v in vals if not np.isnan(v)]
        if not param_vals:
            stats[cat] = {"min": 1.0, "max": 1.0, "goal": goal}
        else:
            stats[cat] = {"min": min(param_vals), "max": max(param_vals), "goal": goal}

    # Normalize
    norm_scores = {l: [] for l in labels}
    
    for i, cat in enumerate(categories):
        s = stats[cat]
        goal = s["goal"]
        
        for l in labels:
            val = raw_values[l][i]
            if np.isnan(val):
                norm_val = 0.0
            else:
                if goal == "max":
                    # x / max (if max is 0, then 0)
                    norm_val = val / s["max"] if s["max"] > 1e-9 else 0.0
                else:
                    # min / x (if x is 0, avoid zero div - assume perfect)
                    norm_val = s["min"] / val if val > 1e-9 else 1.0
            
            norm_scores[l].append(norm_val)
            
    return norm_scores, raw_values, categories

def plot_radar(norm_scores, categories, output_path):
    """Plot Radar Chart."""
    N = len(categories)
    
    # Compute angle for each axis
    angles = [n / float(N) * 2 * pi for n in range(N)]
    angles += angles[:1] # Close the loop
    
    fig, ax = plt.subplots(figsize=(10, 10), subplot_kw=dict(polar=True))
    
    # Draw one axe per variable + labels
    plt.xticks(angles[:-1], categories, size=11)
    
    # Draw ylabels
    ax.set_rlabel_position(0)
    plt.yticks([0.25, 0.5, 0.75, 1.0], ["0.25", "0.50", "0.75", "1.00"], color="grey", size=8)
    plt.ylim(0, 1.1)
    
    # Plot each data
    colors = ['b', 'r', 'g', 'c', 'm', 'y', 'k']
    
    for i, (label, scores) in enumerate(norm_scores.items()):
        values = scores + scores[:1] # Close the loop
        color = colors[i % len(colors)]
        ax.plot(angles, values, linewidth=2, linestyle='solid', label=label, color=color)
        ax.fill(angles, values, color=color, alpha=0.1)

    plt.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1))
    plt.title("Model Comparison (Relative Performance)\nOuter edge = Best in category", size=15, weight='bold', y=1.05)
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"\n✅ Radar chart saved to {output_path}")

def print_table(raw_values, categories):
    """Print Markdown table."""
    labels = list(raw_values.keys())
    
    # Header
    header = "| Metric | " + " | ".join(labels) + " |"
    sep = "|---|" + "|".join(["---"] * len(labels)) + "|"
    
    print("\n" + header)
    print(sep)
    
    for i, cat in enumerate(categories):
        row = f"| {cat} | "
        vals = []
        for l in labels:
            val = raw_values[l][i]
            # Format
            txt = f"{val:.4f}" if not np.isnan(val) else "NaN"
            vals.append(txt)
        row += " | ".join(vals) + " |"
        print(row)
    print("\nNote: For Error metrics (RecErr, Frechet, Gaps), Lower is Better.")
    print("      For Quality metrics (MPR, Top10, TempCov), Higher is Better.")

def main():
    parser = argparse.ArgumentParser(description="Generate Radar Chart comparison.")
    parser.add_argument("--inputs", nargs="+", required=True, 
                        help="List of 'Label:Path' to JSON files. E.g. 'Ours:res_v11.json' 'Base:res_base.json'")
    parser.add_argument("--output", type=str, default="comparison_radar.png", help="Output image path")
    
    args = parser.parse_args()
    
    # Load
    data = load_data(args.inputs)
    if not data:
        print("No valid data loaded.")
        return

    # Process
    norm_scores, raw_values, categories = normalize_scores(data)
    
    # Plot
    plot_radar(norm_scores, categories, args.output)
    
    # Print Table
    print_table(raw_values, categories)

if __name__ == "__main__":
    main()
